api_platform:
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity'

  formats:
    json:
      mime_types: [ 'application/json' ]
    jsonld:
      mime_types: [ 'application/ld+json' ]

  defaults:
    pagination_client_items_per_page: true

  collection:
    pagination:
      items_per_page_parameter_name: perPage
      page_parameter_name: page

  exception_to_status:
    App\Exception\NotFoundException: 404
