version: '3'

services:
  app:
    build: ./
    volumes:
      - "./:/app"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "4433:433"
    volumes:
      - "./ops/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./:/app:ro"
    depends_on:
      - app

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_OUT_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    env_file:
      - .env

volumes:
  db-data:
